# Generated by Django 4.1 on 2022-09-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='watched',
            field=models.BooleanField(),
        ),
    ]
